filebeat.inputs:
  - type: log
    paths:
      - "{{ROOT}}/logs/file*.log"
path.data: "{{ROOT}}/data-log"
# logging:
#   level: debug
output.file:
  rotate_every_kb: 10485760 # 10GB
  path: "{{ROOT}}/out/log"
  filename: output.json
